env:
  browser: true
  commonjs: true
  es2021: true
  mocha: true
extends: airbnb-base
overrides: []
globals:
  it: true
parserOptions:
  ecmaVersion: latest
rules:
  # Let Prettier handle the formatting!
  quotes: "off"
  indent: "off"
  max-len: "off"
  generator-star-spacing: "off"
  comma-dangle: "off"
  function-paren-newline: "off"
  implicit-arrow-linebreak: "off"
  no-restricted-syntax: ["off", "ForOfStatement"]
  no-await-in-loop: "off"
  class-methods-use-this: "off"
  no-plusplus: "off"
  no-continue: "off"
  no-unused-vars: ["error", { "argsIgnorePattern": "^_" }]
  no-param-reassign: "off"
  camelcase: "off"
